development:
  adapter: postgresql
  database: marketviual_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: marketvisual_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: marketvisual_production
  pool: 5
  timeout: 5000
